# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca89f20b7c13bcf795ecd2b87e26b6886b672e695082ebfeee68fb7eae955bcaa666130011935829df4dc2cf577d968ce93a6f3e6a09c07568a0deac4075a014

test:
  secret_key_base: 34ad9e7434a72069f13ca1116396469a5ed99b77c8e48f488f9cc309bc7145da7e7a996af1e9e603492681af9eaaeb6691a5f13a769cfb8f6f10fb9e7548a346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
