# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05e7dcf4530c6e7a719ea0b6dafe67ac0c8863efeb2a029efe12907a888fa128b56cde3a2055fa62aae96fd195154b4f50821a7072283bdb63c92ed7884bfe07

test:
  secret_key_base: 2ca329ce2287368ff1f63b23d3485a3c8847f12c9493ed0f1d396bfee249b73544f674f0d5f2901f583f20608fc70f163f72cf59ea9e5af481e8a703618739e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
